// swift-tools-version: 5.9
//
// Generated by elo-sdk-source/ios/scripts/build-xcframework.sh during
// release publishing. Do not edit manually; rerun the iOS SDK publish
// workflow to regenerate.

import PackageDescription

let package = Package(
    name: "EloAds",
    platforms: [
        .iOS(.v16),
    ],
    products: [
        .library(name: "EloAds", targets: ["EloAds"]),
        .library(
            name: "EloAdsMediationAdMob",
            targets: ["EloAdsMediationAdMob", "EloAdsMediationAdMobDependencies"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
            from: "13.3.0"
        ),
    ],
    targets: [
        .binaryTarget(
            name: "EloAds",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.3.0/EloAds.xcframework.zip",
            checksum: "b3be38bf74fa0571126cc77d5265aac3b28ec08336aa2e9e70c30cda683ce878"
        ),
        .binaryTarget(
            name: "EloAdsMediationAdMob",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.3.0/EloAdsMediationAdMob.xcframework.zip",
            checksum: "a32b5e01062c79e6e8af82e4f0c710fe1a8070bfb16a454da680d45634b525a1"
        ),
        .target(
            name: "EloAdsMediationAdMobDependencies",
            dependencies: [
                "EloAds",
                "EloAdsMediationAdMob",
                .product(
                    name: "GoogleMobileAds",
                    package: "swift-package-manager-google-mobile-ads"
                ),
            ],
            path: "Sources/EloAdsMediationAdMobDependencies"
        ),
    ]
)
