// swift-tools-version: 5.9
//
// Generated by elo-sdk-source/ios/scripts/build-xcframework.sh during
// release publishing. Do not edit manually; rerun the iOS SDK publish
// workflow to regenerate.

import PackageDescription

let package = Package(
    name: "EloAds",
    platforms: [
        .iOS(.v16),
    ],
    products: [
        .library(name: "EloAds", targets: ["EloAds"]),
        .library(
            name: "EloAdsMediationAdMob",
            targets: ["EloAdsMediationAdMob", "EloAdsMediationAdMobDependencies"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/googleads/swift-package-manager-google-mobile-ads.git",
            from: "13.3.0"
        ),
    ],
    targets: [
        .binaryTarget(
            name: "EloAds",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.4.0/EloAds.xcframework.zip",
            checksum: "93cf188bf4b566cbbf0b37c6787538dc4fd1191a5d8bd8a2d49d29feba9836f3"
        ),
        .binaryTarget(
            name: "EloAdsMediationAdMob",
            url: "https://github.com/growlads/elo-ios-sdk/releases/download/0.4.0/EloAdsMediationAdMob.xcframework.zip",
            checksum: "bbc0a7ebc60b83f0885a08a959d92e87227587069f0ae740527ab3c0955255dd"
        ),
        .target(
            name: "EloAdsMediationAdMobDependencies",
            dependencies: [
                "EloAds",
                "EloAdsMediationAdMob",
                .product(
                    name: "GoogleMobileAds",
                    package: "swift-package-manager-google-mobile-ads"
                ),
            ],
            path: "Sources/EloAdsMediationAdMobDependencies"
        ),
    ]
)
